In [5]:
import csv
import pandas as pd
import numpy as np
from collections import defaultdict

In [2]:
base = "CME"

In [7]:
def cov(comparison, base_name, sec_name):
    if isinstance(comparison,str):
        df_comp = pd.read_csv(comparison)
    elif isinstance(comparison,df.Dataframe):
      df_comp = comparison
    else:
        print("Must be path to csv or pandas dataframe!")
        return

    M_comp = df_comp.to_numpy()

    ID_vec = defaultdict(list)

    for ID in M_comp:
        ID_vec[ID[0]].append(ID)
    
    for ID_val in ID_vec:
        ID_vec[ID_val] = np.array(ID_vec[ID_val]) 
    
    ID_list = np.zeros((len(ID_vec),5), dtype=object)

    for i, ID in enumerate(ID_vec):
        ID_val = ID_vec[ID]
        track_coverage = np.sum(ID_val[:,15] < 3.5)
        missing_t = ID_val[ID_val[:, 15] > 3.5][:,8]
        ID_list[i][0] = ID_val[0][0]
        ID_list[i][1] = ID_val[0][13]
        ID_list[i][2] = track_coverage
        ID_list[i][3] = missing_t.tolist()
        block_starts = np.where(np.diff(ID_val[:,1]) != 0)[0] + 1
        block_starts = np.insert(block_starts, 0, 0)
        track_index = np.where(np.diff(ID_val[:,1]) != 0)[0] + 1
        track_index = np.insert(track_index, 0, 0)
        y_ID = ID_val[:,1][block_starts]
        track_lengths = ID_val[:,14][track_index]
        y = np.stack((y_ID,block_starts+1,track_lengths), axis=1)
        y_all = ';'.join([','.join(map(str, row)) for row in y])
        ID_list[i][4] = y_all

    df_ID = pd.DataFrame(ID_list, columns = [f"ID ({base_name})",f"Track Length ({base_name})",f"Track Coverage", "Missing Time Points",f"{sec_name} Data"])

    return df_ID
    

cov("CME Base Output/Comparison.csv", "CME", "Dino")

,ID (CME),Track Length (CME),Track Coverage,Missing Time Points,Dino Data
0,2.0,99.0,99,[],"244.0,1,99.0"
1,3.0,99.0,99,[],"370.0,1,13.0;380.0,14,99.0"
2,4.0,99.0,99,[],"392.0,1,99.0"
3,5.0,99.0,99,[],"415.0,1,99.0"
4,7.0,99.0,99,[],"447.0,1,99.0"
...,...,...,...,...,...
10509,10787.0,2.0,0,"[98.0, 99.0]","20399.0,1,33.0"
10510,10788.0,2.0,2,[],"29431.0,1,2.0"
10511,10789.0,2.0,1,[99.0],"29448.0,1,1.0;27027.0,2,9.0"
10512,10790.0,2.0,0,"[98.0, 99.0]","26559.0,1,12.0"
10513,10791.0,2.0,0,"[98.0, 99.0]","27787.0,1,8.0;26084.0,2,16.0"

In [6]:
df_ID = pd.DataFrame(ID_list, columns = [f"ID ({base})",f"Track Length ({base})",f"Track Coverage","Missing Time Points",f"{sec} Data"])

In [7]:
df_ID.to_csv(f"{base} Base Output/ID_Coverage.csv", index=False)

In [8]:
df_ID

,ID (CME),Track Length (CME),Track Coverage,Missing Time Points,Dino Data
0,2.0,99.0,99,[],"244.0,1,99.0"
1,3.0,99.0,99,[],"370.0,1,13.0;380.0,14,99.0"
2,4.0,99.0,99,[],"392.0,1,99.0"
3,5.0,99.0,99,[],"415.0,1,99.0"
4,7.0,99.0,99,[],"447.0,1,99.0"
...,...,...,...,...,...
10509,10787.0,2.0,0,"[98.0, 99.0]","20399.0,1,33.0"
10510,10788.0,2.0,2,[],"29431.0,1,2.0"
10511,10789.0,2.0,1,[99.0],"29448.0,1,1.0;27027.0,2,9.0"
10512,10790.0,2.0,0,"[98.0, 99.0]","26559.0,1,12.0"
10513,10791.0,2.0,0,"[98.0, 99.0]","27787.0,1,8.0;26084.0,2,16.0"

In [11]:
a = pd.read_csv("Input Data/detections_CME.csv",names=["t","ID","x","y","z","FI"])
]
a.to_csv("detections_CME.csv")